### ISSUE TITLE
Usage with Guzzle5

### ISSUE THREAD

**Issue by Nyholm** [google/google-auth-library-php#102]
If you create a project with the following composer.json. How can I get it to work? The readme suggest using HandlerStack but that is only available in Guzzle6. Am I missing something?

```yaml
"require": {
        "google/auth": "^0.7.0",
        "guzzlehttp/guzzle": "^5.0"
    }
```
